name = "vibrantCrankshaft"
version = "1.0.0"
link = "https://github.com/ShadowBlip/vibrantCrankshaft"
source = "https://github.com/ShadowBlip/vibrantCrankshaft"
min-crankshaft-version = "0.2.4"

[author]
name = "William Edwards"
link = "https://github.com/ShadowApex"

[entrypoints]

	[entrypoints.desktop]
	library = false
	menu = false

	[entrypoints.deck]
	library = false
	menu = false
	quick-access = true

[store]
description = """
Set vibrancy (saturation) of your screen.

Based off of vibrantDeck from Scrumplex.
"""

